### ISSUE TITLE
Missing membership list in people profiles

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#102]
# Context
The button exists, now we need to create the page

# Todo
- [x] create the page
- [x] lists memberships
- [x] differentiate active/non active memberships

**Comment by LucileDT** [comment]
Todo :
- [ ] fix date error
- [ ] fix copy-paste error
- [ ] order by date the old memberships

**Comment by LucileDT** [comment]
- [ ] add the memberships list to non members too

**Comment by Yann-BUTSCHER-EIRL** [comment]
Done but there is a minor bug. It has been referenced under issue #117 .
Closing this one anyway.
