### ISSUE TITLE
Show people information recap when they are selected

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#108]
# Context
In the membership creation page, we need to show one person information when they are selected.

# Todo
- [x] Create a rest controller in a new file
  - [x] Configure routing
  - [x] Configure security
  - [x] Create a method that gets a People given it's id
  - [x] Install dependencies
    - [x] Add them to the bundle list
    - [x] Configure them if needed
- [x] Call the new route when adding a people to the membership
- [x] Show the recap to the user by adding it to the view

**Comment by Yann-BUTSCHER-EIRL** [comment]
Finished. Can be tested at http://localhost:8000/ajax/people/{id}
