### ISSUE TITLE
Translate the website in English

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#109]
# Context
Currently the website is only written in French. We will add an english translation to it using Crowdin.

# Todo
- [x] setup the project
- [x] add trans tags into templates
- [x] setup Crowdin integration
- [x] translate the website

**Comment by LucileDT** [comment]
@hundrex just make an overall check. We will create new issues when encountering bugs using Structura, no need to pressure yourself.

**Comment by hundrex** [comment]
Works okayish, opened some issues for some translation missing, more will be opened when found.
