### ISSUE TITLE
Update the number of people you can add to a membership dynamically

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#111]
# Context
It would be useful to be able to access one MembershipType information in order to update the number of people you can add to a Membership when selecting a new MembershipType in the create/edit Membership page.

A nice technical solution is to make an ajax call to get the MembershipType we want. For this we need an MembershipTypeAjaxController.

# Todo
- [x] Create a rest controller in a new file
  - [x] Configure routing
  - [x] Configure security
  - [x] Create a method that gets a MembershipType given it's id
- [x] Call the new route when the MembershipType is changed
   - [x] Then update the max number of people a membership can have
