### ISSUE TITLE
Update the project documentation

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#114]
# Context
We slacked a bit the documentation this last months so we need to check every project's procedure up in order to have an updated documentation.

# Todo
- [ ] Check every existing parts of the documentation and create a sub-issue if documentation is lacking
  - [ ] A-1. Utilisation : Base
  - [ ] A-2. Utilisation : Partie administration
  - [ ] B. Installation
  - [ ] C-1. Contribution : Démarrer
  - [ ] C-2. Contribution : Rôles
  - [ ] C-3. Contribution : Conventions de codage
  - [ ] C-4. Contribution : Écrire et faire passer des tests
