### ISSUE TITLE
Export the project's documentation to new wiki

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#115]
# Context
Since the github wiki was found to be a bit difficult to use and hardly offers translation support, we need to find a better platform and export all the documentation in it.

# Todo
- [x] Make an comparative study about existing wiki solutions with pros and cons.
- [x] Choose between a solution (please note in comment which one has been chosen and why)
- [ ] Host it on a server the will allow the wiki to be online
  - [x] Install the program on the server
  - [ ] Make the wiki accessible from the web
  - [ ] Document the installation procedure
- [ ] Export the documentation to the new platform

**Comment by LucileDT** [comment]
We will use [Docu Wiki](https://www.dokuwiki.org) because:
- it's open source
- it supports natively the translation (which MediaWiki doesn't)
- it's supported and has regular updates
