### ISSUE TITLE
Translate the documentation

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#116]
# Context
We need to offer contributors all the resources for them to be able to work on the project. Having a documentation available both in french and english would help to provide said resources for a wider number of contributors.

But beforehands we need to update the documentation (detailed in a different issue) and to change our wiki plateform (also detailed in a separate issue) since the one on github doesn't support translation.

# Todo
- [ ] Update the documentation - #114 
- [ ] Export the project to a new wiki - #115 
- [ ] Have the french translation done
- [ ] Have the english translation done
