### ISSUE TITLE
Add a membership edition page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#118]
# Context
We need to be able to edit a membership information.

# Todo
- [x] Show the current members' recap at the page's opening
- [x] Use all of the creation page behaviors to be consistent to the user
  - [x] Change default amount of the membership when it's type is changed.
  - [x] Remove all members when the membership type is changed.
  - [x] Add/Remove the people's recap when a people is Added/Removed
  - [x] The total amount to pay must be updated when the membership or the donation amount changes.
  - [x] Disable the select list of new members when the maximum amount of members is reached.
  - [x] Add a menu in the membership show page in order to put a link to the membership edition page

**Comment by hundrex** [comment]
@Yann-BUTSCHER-EIRL Frontend OK when editing a family membership, but whenever I try to edit a normal one, I just have this error when opening the edition page : 
`Return value of App\Entity\Payment::getPayer() must be an instance of App\Entity\People, null returned`
![image](https://user-images.githubusercontent.com/11696314/75694951-9c50f080-5ca9-11ea-8219-2da8bcb4d374.png)

**Comment by Yann-BUTSCHER-EIRL** [comment]
I think it's a database problem. The fixtures are not adding a payer to a payment and this is causing this error.

I'll fix the fixtures in a separate issue and then you would be able to reload your database and test again.

**Comment by Yann-BUTSCHER-EIRL** [comment]
This should be fixed now, can you test it again @hundrex ? 

Please remember to reset your database first before doing it.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Edited the issue to add an item in the todo list : 
> Add a menu in the membership show page in order to put a link to the membership edition page

**Comment by LucileDT** [comment]
An error happens when loading fixtures

```
lapis@lapis-VirtualBox:~/developpement/structura$ bin/console doctrine:fixtures:load --append

   > loading App\DataFixtures\UserFixtures
   > loading App\DataFixtures\MembershipFixtures
   > loading App\DataFixtures\DonationFixtures
   > loading App\DataFixtures\TranslationFixtures

In MappingException.php line 94:
                                                          
  Class 'App\DataFixtures\MembershipType' does not exist  
```

**Comment by LucileDT** [comment]
See #159

**Comment by LucileDT** [comment]
![image](https://user-images.githubusercontent.com/23707217/76241139-d172bb00-6234-11ea-9b7b-b7b543159b02.png)

Confirmation modal is broken
