### ISSUE TITLE
Make the membership creation page more user-friendly

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#119]
# Context
When need to rework the membership creation page since it's hardly usable.

# Mockups
![membership-create-mockup](https://user-images.githubusercontent.com/50443097/73832564-b57c9380-4808-11ea-9a4d-db28876ba2a6.jpg)
![membership-create-summary-mockup](https://user-images.githubusercontent.com/50443097/73832567-b6adc080-4808-11ea-84e7-7b6680c9bfdb.jpg)

# Todo
- [x] Make a new and clean mockup
- [x] Update this issue to list the changes
- [x] Apply changes to the page
  - [x] Add placeholders for selected people's info
  - [x] Add a third column to spread more evenly the form's fields
  - [x] Make the commentary fields larger and at the bottom of the columns
  - [x] Add a search fields to the user selection list
  - [x] Add a fiscal year field
  - [x] Only the payment field must be editable
     - [x] membership and donation are automatically calculated
  - [x] display the different rows after the previous one being filled
  - [x] Add a summary pop up before submitting the form.

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL could you please add a picture of the mockups in the issue?

**Comment by LucileDT** [comment]
And also update the todo list

**Comment by LucileDT** [comment]
Ok for me, @hundrex what do you think?

**Comment by hundrex** [comment]
Ok for me too, closing issue.
