### ISSUE TITLE
Upgrade the project to version 4.3.10 to fix security vulnerabilities

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#120]
# Context
Since security vulnerabilities has been identified in our current symfony version, we need to upgrade it.

# Todo
- [x] Change the symfony version
- [x] Update the packages
- [x] Check in the symfony helper that there is no errors.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Please can you test this one @LucileDT ?
