### ISSUE TITLE
Fix the project deprecation

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#121]
# Context
Since the project has been updated to v4.3.10 (#120 ) some deprecations appeared. It would be nice to fix them but this is not top priority.

# Todo
- [x] Fix the listed dependencies in the symfony profiler
  - [x] User  Deprecated: Creating Doctrine\ORM\Mapping\UnderscoreNamingStrategy  without making it number aware is deprecated and will be removed in  Doctrine ORM 3.0.
  - [x] The "App\Controller\Ajax\MembershipTypeAjaxController" class extends "FOS\RestBundle\Controller\FOSRestController" that is deprecated since FOSRestBundle 2.5, use {see AbstractFOSRestController} instead.
  - [x] The "App\Controller\Ajax\PeopleAjaxController" class extends "FOS\RestBundle\Controller\FOSRestController" that is deprecated since FOSRestBundle 2.5, use {see AbstractFOSRestController} instead.
  - [x] Configuring an encoder with "bcrypt" as algorithm is deprecated since Symfony 4.3, use "auto" instead.
  - [x] Creating  Doctrine\ORM\Mapping\UnderscoreNamingStrategy without making it number  aware is deprecated and will be removed in Doctrine ORM 3.0.
  - [x] Using an "if" condition on "for" tag in "Home/_locale_switcher.html.twig" at line 6 is deprecated since Twig 2.10.0, use a "filter" filter or an "if" condition inside the "for" body instead (if your condition depends on a variable updated inside the loop).

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT I fixed all the deprecations that I could without upgrading the symfony version since the remaining deprecations comes from composer packages that can't be upgraded with our current symfony version.

The remaining deprecations are:
- JMS\SerializerBundle\DependencyInjection\Compiler\ServiceMapPass  implements the Serializable interface, which is deprecated. Implement  __serialize() and __unserialize() instead (or in addition, if support  for old PHP versions is necessary)
- The "Symfony\Bridge\Doctrine\Logger\DbalLogger" class implements "Doctrine\DBAL\Logging\SQLLogger" that is deprecated Use {@see \Doctrine\DBAL\Logging\Middleware} or implement {@see \Doctrine\DBAL\Driver\Middleware} instead.

I'll create an issue to update Symfony to version 5.4 (LTS) but I think we can close this one (after testing).

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I agree but we need to plan a day to test the whole app + write our scenarii down for future use if we want to add automatic functional testing to Structura. Can you add a reminder in our agenda?

**Comment by Yann-BUTSCHER-EIRL** [comment]
It has been done.
