### ISSUE TITLE
Add a title to each page so we can see what the page is about in browser tabs

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#126]
# Context
When navigating around the application, the user might want to have multiple tabs opened. A title would help to now what each tab is about to help switch between them.

# Todo
- [x] Add a title tag to each of those pages with a precise title of what the page is about
  - [x] / (home)
  - [x] /member
  - [x] /member/X (user details)
  - [x] /member/X/memberships
  - [x] /member/X/edit
  - [x] /people
  - [x] /people/X
  - [x] /people/X/memberships
  - [x] /people/X/edit
  - [x] /membership
  - [x] /membership/X
  - [x] /membership/X/edit
  - [x] /membership/new
  - [x] /donation
  - [x] /donation/X
  - [x] /donation/X/edit
  - [x] /donation/new
  - [x] /administration
  - [x] /user
  - [x] /user/X
  - [x] /user/X/history
  - [x] /user/X/edit
  - [x] /user/new/dashboard
  - [x] /profile/X
  - [x] /profile/X/editpassword
  - [x] /profile/X/editpseudonym
  - [x] profile/X/editpersonal
  - [x] profile/X/editnewsletter
  - [x] /login

**Comment by LucileDT** [comment]
@hundrex could you please list all the pages missing a specific title? Would be easier to work with it.
