### ISSUE TITLE
Attach top nav bar and detach footer

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#127]
# Context
While navigating in the application, the navbar is very useful, but is is not fixed right now, and so it disappears when scrolling down. It would be better to attach it so that it stays usable wherever we are on the page.
On the contrary, the footer is currently attached, so it is visible even when the user is able to scroll down. Although, it serves no purpose whatsoever in navigating the application, and is even annoying to have when information are behind on scrollable pages. 

# Todo
- [x] Attach the top navbar
- [x] Detach the footer

**Comment by hundrex** [comment]
Reopened because it breaks some pages.

**Comment by LucileDT** [comment]
- [ ] make the footer go to the bottom of the page
- [ ] messages are hidden behind the top navbar
