### ISSUE TITLE
Add person that paid on membership information

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#140]
# Context
For family type adhesion, there is no way to know who paid for it, this information is neither present on the membership section of the members, nor on the membership page. It could be useful to know who made the payment.

# Todo
- [x] add a field in membership to register the person who paid for it
- [x] add a field in membership registration form to register that information
- [x] show this information on the membership section of the members page
- [x] show this information on the membership page

**Comment by LucileDT** [comment]
I do not understand, this is already done (see membership creation page), could you please explain on which screen the people who paid is not displayed?

**Comment by hundrex** [comment]
It was indeed already present in the membership registration form, but then this information is not shown in any page where we can see membership information, so neither on the membership section of a member profile, nor on the membership details page.

**Comment by Yann-BUTSCHER-EIRL** [comment]
@hundrex Can you test it please?

**Comment by LucileDT** [comment]
Would be nice to create a new issue to make it more user friendly, but otherwise, it works.
