### ISSUE TITLE
Add link to user page where users names are shown

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#141]
# Context
There are some page where there are user names in small boxes (except for donation pages). It would be great to make those boxes clickable and redirect to the user page for quick navigation.

# Todo
- [x] Add link to the second person in the family membership when consulting a member membership section (_/member/X/memberships_ and _/people/X/memberships_ urls)
- [x] Add link to user in memberships pages (_/membership/X_ urls)
- [x] Add link to user in donation pages (_/donation/X_ urls)
