### ISSUE TITLE
Add name of member in membership and donation titles

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#142]
# Context
When watching the membership section of a member, or the donation pages, the title does not indicate the concerned user name. Putting that information in the tittle would allow for easier navigation back and forth the multiple tabs people may have opened.

# Todo
- [ ] put member name at the end of the title for membership section of member pages instead of `l'utilisateurice` (_/member/X/memberships_ urls): instead of `Liste des adhésions de l'utilisateurice ` there should be `Liste des adhésions de <member_name> `
- [ ] add donator name at the end of the tittle on donation pages (_/donation/X_ urls): `Don de XX€ du JJ Mmm. YYYY de <donator_name>`

**Comment by LucileDT** [comment]
You should check:
- [ ] memberships section under people's profile
  - [ ] /people/x/memberships subtitle
  - [ ] /people/x/memberships breadcrumb
  - [ ] /member/x/memberships subtitle
  - [ ] /member/x/memberships breadcrumb
- [ ] donation preview page
  - [ ] breadcrumb
  - [ ] subtitle
