### ISSUE TITLE
Separate into two pages the password edition and the user data edition forms

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#146]
# Context
Currently, the user edition page has two forms in it. We should separate those forms into two different page, with one form by page.

The side menu should also be edited to look like the Edit profile one: there would be a button for each page in it.

# Todo
- [ ] separate the two forms
  - [ ] edit controller (create two methods)
  - [ ] create a new view for the password form
  - [ ] edit the edit view of the user (also rename it)
- [ ] uniformize the page 
  - [ ] edit side menu to have a link to both pages
  - [ ] add "return to user profile" buttons on bottom of each form
