### ISSUE TITLE
Use fixture sharing object feature instead of retreiving data from the database

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#160]
# Context
We currently select object from the database in the fixtures using their labels but the fixtures bundle provides a better way to use previously created objects: https://symfony.com/doc/master/bundles/DoctrineFixturesBundle/index.html#sharing-objects-between-fixtures

We should use this method instead as it is clearer, faster, and less prone to errors.

# Todo
- [ ] update user fixtures
- [ ] update translation fixtures
- [ ] update membership fixtures
- [ ] update donation fixtures
