### ISSUE TITLE
Tooltip of export button not translated on member list page

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#173]
# Context
The tooltip for the three exporting buttons on top of the member list page (/member) are not translated.

# Todo
- [ ] add translation for copy/paste button
- [ ] add translation for csv export button
- [ ] add translation for pdf export button

**Comment by LucileDT** [comment]
Closing as we drop Structura localization for now
