### ISSUE TITLE
Many fields and tooltip not translated on member membership page

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#174]
# Context
Many field on the member membership page ( /member/X/memberships ) are not translated 
Here is the list from top to bottom: 
- Title
- Breadcrumb
- Page title 
- "Adhésion d'une famille à l'association pour une année."
- "__Adhésion du 30 Apr. 2020 to 30 Apr. 2021 "
- Tooltip of Other members involved
In case of older membership there are the same fields not translated.

# Todo
- [ ] add translation for Title
- [ ] add translation for Breadcrumb
- [ ] add translation for Page tittle
- [ ] add translation for "Adhésion d'une famille à l'association pour une année."
- [ ] add translation for "__Adhésion du 30 Apr. 2020 to 30 Apr. 2021 "
- [ ] add translation for Tooltip of Other members involved
- [ ] make sure the modification also affect the old memberships

**Comment by LucileDT** [comment]
We will stop Structura localization for now as it is not a priority for our users
