### ISSUE TITLE
Upgrade Ionicon version

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#176]
# Context
Currently we use Ionicons v4.4.6. The problem is that the documentation is only available for 5.0.0 versions and above. We need to update our version to be up to date.

# Todo
- [ ] update library
  - [ ] on composer install, dl the library
  - [ ] update base.html.twig to add the js tag to load the library
  - [ ] remove the ionicon css call in global.css
- [ ] update code
  - [ ] replace all the icon tags by the new way to call Ionicons icons

**Comment by LucileDT** [comment]
Ionicon has been replaced by RemixIcon
