### ISSUE TITLE
Add a tax receipts page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#177]
# Context
We need a page that allow the manager to generate and download a tax receipts PDF for all users given a fiscal year. 

# Todo
- [x] Add the link in the navbar
- [x] Create the page
- [x] Make page look like mockups
- [x] Implements features for this page 
  - [x] #178
  - [x] #179

![image](https://user-images.githubusercontent.com/23707217/81423554-e3011200-9154-11ea-9da2-0dd69e8fe4be.png)
