### ISSUE TITLE
Add a button to generate tax receipts PDF in Tax receipts page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#178]
# Context
When a manager is in the Tax receipts page, they need a button that will generate a PDF containing the tax receipts for all users given a fiscal year.

# Todo
- [x] frontend 
  - [x] Add the fiscal year selector (dropdown list)
  - [x] Add the button
  - [x] When clicked, the user shouldn't be able to click again until the document is fully generated
  - [x] Add a confirmation message when the document is finished
- [x] backend
  - [x] receipt entity/repository (see also #169) 
  - [x] receipt service
  - [x] job
    - [x] file generation (see attached picture)
    - [x] update database entry to know if the job is running or has finished

![image](https://user-images.githubusercontent.com/23707217/81424044-9a962400-9155-11ea-8fa2-670396e1dad0.png)

![image](https://user-images.githubusercontent.com/23707217/81424319-05dff600-9156-11ea-8cd1-a14cb51ca563.png)

![image](https://user-images.githubusercontent.com/23707217/81424480-535c6300-9156-11ea-9195-f245f35f0722.png)

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I pushed the template for a receipt. It's missing 3 pictures (association logo, signature and a pair of scissors to show where to cut the paper - for this one I'm very sad that our library isn't able to render Ionicons -_-) so I will not check `file generation`.

Could you please think about how we can add pics in the template technically? I don't know if I want them on the repo given that one of it is a signature...

Thanks :pray:

**Comment by LucileDT** [comment]
@hundrex to test all those functionalities, you will have to run `bin/console messenger:consume -vv` in a terminal as it is the background process that take care of the files generation
