### ISSUE TITLE
More diverse fixtures

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#180]
# Context
We use fixtures to fill our databases in local. Currently, all the phone numbers are the same, and a lot of addresses are identical. We should make them more different to better see the filled fields in generated PDF.

# Todo
- [x] generate different phone numbers
- [x] generate different addresses
- [x] generate different membership dates 
- [x] generate different payment dates

**Comment by hundrex** [comment]
I still have the same membership dates for all the memberships ( 13 May 2020 to 13 May 2021).
Ok for the others items.
