### ISSUE TITLE
Generate receipt PDF between two dates

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#181]
# Context
To allow managers to generate receipts not only for a whole year.

# Todo
- [x] create the form
- [x] generation of receipts
- [x] page where manager can get the freshly generated receipt

![image](https://user-images.githubusercontent.com/23707217/81424773-c1a12580-9156-11ea-8c65-04501dae5ff8.png)
