### ISSUE TITLE
Add a way to delete generated receipts

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#190]
# Context
When generating many receipts, they can easily pile up, and some may not be wanted to be kept by the user at some point. A simple solution would be to add a button (with a confirmation) to be able to delete the receipts that are not wanted anymore. The user would then be able to select what they keep and what they don't.

# Todo
- [ ] add a delete button next to the download button on the receipt tables lines
- [ ] add a confirmation modal to warn the user
- [ ] implement the deletion in backend

**Comment by Yann-BUTSCHER-EIRL** [comment]
The corresponding file should be deleted too.
