### ISSUE TITLE
Improve the Receipt's entity order code managment

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#192]
# Context
We need to make sure for legal reasons that once the order code is generated for a `Receipt`, it stays the same. For now, we are regenerating it each time and it's could be not consistent.
We should save it in the database once generated (and not edit it ever again) to address that problem.

Also, the order code is now depending of the payment's fiscal year which is problematic since this value could be edited (and by consequence, change the order code). 
We need to change that behaviour and make sure the order code "year" part is the `Receipt` creation year.

# Todo
- [x] Add a new field `orderCode` in database
- [x] Update the existing receipts via a new migration
- [x] Rename the `fiscalYear` field to `year`
- [x] Change the way the year field is added to a receipt

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL do you want to continue this issue or is it okay the way it is?

**Comment by Yann-BUTSCHER-EIRL** [comment]
We should finish this one because it would cause usage problems in the future.
I'll do it this weekend maybe.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Renaming finished. Also, the year of a Receipt is set to the year of the Receipt creation.
Please don't hesitate to test all of the pages and features that generate a receipt from a year since a lot of names have been renamed. I tested as much as I can but I might have forgotten some.

**Comment by LucileDT** [comment]
You broke the migrations
