### ISSUE TITLE
Add missing pictures in receipts

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#199]
# Context
Our templates are missing pictures (association logo, signature, icon to show that a part is cutable...). We need to add them.

# Todo
- [x] create a system to upload pictures in the Administration
  - [x] asso logo
  - [x] signature
- [x] add scissors icon to the project
- [x] add pictures to pdf
  - [x] logo
  - [x] signature
  - [x] scissors

**Comment by LucileDT** [comment]
@Parmifer the PHP GD extension will be needed to allow the generation of pdf using png pictures, how could we notice that this extension is mandatory?
