### ISSUE TITLE
Add an installer to Structura

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#206]
# Context
Currently we can't easily install Structura if we don't use the fixtures. We need an installer to at least create an admin account.

# Todo
- [x] create a sh script to install Structura
  - [x] composer install
  - [x] create database
  - [x] execute migrations
  - [x] create admin account
  - [x] run message service? explain that this should be run each time the server is started

**Comment by hundrex** [comment]
Opened #223 that needs to be done for this to be validated.
