### ISSUE TITLE
Tag a People as a Contact

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#211]
# Context
As stated in the meta-issue #210, we need to be able to know if the person is a "Contact" (e.g. MDPH/MDA privileged correspondant, partners for events, etc.) and create a specific directory for this person.

# Todo
- [x] Be able to identify people as Contact
  - [x] add field in creation form
  - [x] add field in edit form
  - [x] show badge on people detail page
- [x] Create a distinct directory for them
