### ISSUE TITLE
Tag a People as Social Pole user

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#212]
# Context
As stated in the meta-issue #210, we need to be able to know if the person is in relation with the association's "Social Pole" (e.g. ill person, concerned with the HD, or just anyone who need social help).

Once this is done, we need to show it if the user can see sensible information.

# Todo

- [x] If the connected user can see sensible information:
  - [x] Be able to identify people as Social Pole user  
    - [x] add field in creation form
    - [x] add field in edition form
  - [x] Show the information in the People detail
  - [x] Show the information in the Member detail
