### ISSUE TITLE
Show city and postal code in directories

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#213]
# Context
We need to be able to see the city and the postal code of the people listed in the directories. We also need them to be sortable.

# Todo
- [x] Add a city column for each directories
  - [x] Must be sortable
- [x] Add a postal code column for each directories
  - [x] Must be sortable
