### ISSUE TITLE
Add check information when a payment is made by check

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#214]
# Context
When someone pay by check we have to store more information. For this we need to update the forms that saves a payment into the application but also show this information when the payment is shown somewhere in Structura.

# Todo
- [x] Add the missing information
  - [x] Check number
  - [x] Check date
  - [x] Bank name 
    - [x] Must be selected from a list (see #215)
  - [x] Check emitter (the person whose name is on the check)
- [x] Show the payment information

**Comment by LucileDT** [comment]
# Checklist
- [ ] membership creation form
  - [ ] check number
  - [ ] check date
  - [ ] bank name
  - [ ] check issuer
  - [ ] rework of the form
- [ ] membership edition form
  - [ ] check number
  - [ ] check date
  - [ ] bank name
  - [ ] check issuer
  - [ ] rework of the form
- [ ] membership details page
  - [ ] check number
  - [ ] check date
  - [ ] bank name
  - [ ] check issuer
  - [ ] rework of the page

**Comment by Yann-BUTSCHER-EIRL** [comment]
The check's date is missing on the donation detail page. It would be nice to add it after the check number.

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL See #268
