### ISSUE TITLE
Save a bank name list into Structura

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#215]
# Context
When someone pay by check we need to identify the check's bank. For this we need a list for bank names that is saved in the application.

# Todo
- [x] Add a new entity "Bank" with the following fields
  - [x] id : int - primary key
  - [x] name :  string - unique - required
- [x] Add bank select on forms 
  - [x] donation
    - [x] creation
      - [x] show when payment type is `check`
      - [x] hide on other payment types
        - [x] hidden by default
        - [x] hidden when selected
    - [x] edition
      - [x] show when payment type is `check`
      - [x] hide on other payment types
        - [x] hidden by default
        - [x] hidden when selected
  - [x] membership
    - [x] creation
      - [x] show when payment type is `check`
      - [x] hide on other payment types
        - [x] hidden by default
        - [x] hidden when selected
    - [x] edition
      - [x] show when payment type is `check`
      - [x] hide on other payment types
        - [x] hidden by default
        - [x] hidden when selected
- [x] Show bank in detail pages
  - [x] membership show
  - [x] donation show
- [x] Add CRU pages in Administration to save new Banks
  - [x] create
  - [x] show
  - [x] update

Additionally (we need to change our select library):
- [x] replace bootstrap select by Select2 on forms where it's used
  - [x] membership creation form
  - [x] membership edition form
  - [x] donation creation form
  - [x] donation edition form

**Comment by LucileDT** [comment]
@Yann-BUTSCHER-EIRL I think making the bank creation available in the dropdown is too difficult for now. I propose we add a regular CRUD pages for it as it will be faster to make and easier to maintain.

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT It's ok for me but we need to create an issue for the dropdown later realisation.

**Comment by LucileDT** [comment]
I'll let you do it.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Created the issue #237.
Updated the todo list and the context accordingly.
