### ISSUE TITLE
Do not generate fiscal receipts if the payment was made on HelloAsso

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#216]
# Context
Since HelloAsso generates its own fiscal receipts we don't want to have two different receipts for a same payment.

# Todo
- [x] Prevent receipt generation if the payment type is HelloAsso
  - [x] between two dates
  - [x] by year
  - [x] from people profile

**Comment by Yann-BUTSCHER-EIRL** [comment]
I've tested and it works. Closing.
