### ISSUE TITLE
Save the first contact year for a person.

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#217]
# Context
We need to save the year which a person has been added to the application and show it under "First contact" label.

# Todo
- [ ] Save the year when a person is created automatically (current year)
- [ ] Show this information
- [ ] Must be editable

**Comment by hundrex** [comment]
I've got the following error when trying to edit a member/people, so I can't test any further: 
```
An exception occurred while executing 'INSERT INTO peoples_people_types (people_id, people_type_id) VALUES (?, ?)' with params [10, 2]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '10-2' for key 'PRIMARY'
```

**Comment by hundrex** [comment]
The first contact year is not in the edit forms anymore, so I can't test it.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Tested and it works. Closing.
