### ISSUE TITLE
Add a filter on top of the member directory list

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#218]
# Context
In addition of the search bar that is present on the member list, we want to be able to filter them on fixed criteria.

Each criteria will be show with a checkbox that update the list when ticked ou unticked. Multiple filter criterias can be applied at the same time

# Todo
- [ ] Add the following filters :
  - [ ] Member department 
    - [ ] Each department must be checkable independently  
    - [ ] Add a "Check all" checkbox
  - [ ] Is Pole Social user ?
  - [ ] Is Contact ?
