### ISSUE TITLE
Add graph based on real data on homepage

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#225]
# Context
Currently there is a graph on the homepage. It's a placeholder. We want to make it dynamic and based on Structura data.

# Todo
- [x] add graph
  - [x] show amount memberships
  - [x] show amount donations
  - [x] show sum memberships&donation amounts

**Comment by hundrex** [comment]
Please confirm that the data shown should indeed be with the cashing date (as it is now) and not with the date of the event (membership or donation date).

**Comment by LucileDT** [comment]
I made it be the cashing date, as I think that it is more meaningful to see when the association get money, instead of when it collects it. Do you find this choice pertinent?
