### ISSUE TITLE
Add tag generation page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#230]
# Context
When our end users need to send paper mail to all their contacts, they need to print a list of all the people's addresses to ease the process. We need to create a page that permits to generate a PDF file of these addresses.

# Todo
- [x] Create a tag page with a "Generate tags" button
- [x] When clicking on this button, the PDF must be generated with a background worker. 
- [x] A button must be available to download the file once the generation has ended.
- [x] A message to show when generation is done

**Comment by Yann-BUTSCHER-EIRL** [comment]
I need to fix the pull request reviews before merging.

**Comment by Yann-BUTSCHER-EIRL** [comment]
It would be nice to change the download button in a more user friendly way, by notifying the user when the generation is finished.
