### ISSUE TITLE
Make bank creation available in dropdown lists

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#237]
# Context
When someone pay by check we need to identify the check's bank. There is an issue (#215) for that but, we also need to be able to add a new bank "on the go".

To be able to do that, we should make the bank dropdown writeable and, when a new bank is added, save it.

When saving the bank name we need to sanitize the user input to prevent double entries.

# Todo
- [ ] Make bank creation available in dropdown lists
  - [ ] donation creation form
  - [ ] donation edition form
  - [ ] membership creation form
  - [ ] membership edition form 
- [ ] On bank creation, sanitize user input (in this order)
  - [ ] Trim all fore and end spaces
  - [ ] To lower case
  - [ ] No more that one following space (remove double, triple space)
  - [ ] Uppercase the first letter for each sub-string separated by one space
