### ISSUE TITLE
Mandatory fields in the membership creation/edition forms are not shown as if they were

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#240]
# Scenario
Go to membership creation page (/membership/new).
Select Simple membership.
Select a person.
Click the "Create" button.

# Expected behavior
The mandatory fields should fail validation and show the user an error saying that they are indeed mandatory. 
Asteriks should be shown next to the mandatory fields names.

# Current behavior
The form is submitted and validated. The server returns a 500 error.

# Todo
- [x] creation form
  - [x] Mark the fields as mandatory
  - [x] Add a visual indicator showing they are mandatory
  - [x] If the mandatory fields are not set, the form validation must fail
- [x] edition form
  - [x] Mark the fields as mandatory
  - [x] Add a visual indicator showing they are mandatory
  - [x] If the mandatory fields are not set, the form validation must fail

**Comment by LucileDT** [comment]
Missing the edit form.

**Comment by hundrex** [comment]
Edition form does not have the sentence "Les champs notés avec * sont requis." neither the "*" to mark which fields are required.
