### ISSUE TITLE
Add a second address line

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#242]
# Context
Some addresses are really long and to make them more readable, we must add a second address line.

# Todo
- [x] Add a second address line in the person/member forms
- [x] Show the second address line in those locations:
  - [x] Person profile
  - [x] Member profile
  - [x] My profile
  - [x] Membership forms
  - [x] Tags
  - [x] Fiscal receipts
  - [x] Old members table (in the home page)

**Comment by hundrex** [comment]
The line is missing form `people/new`

**Comment by Yann-BUTSCHER-EIRL** [comment]
I found it in people/new.

Note that the branch to use for testing this is `hotfixes`
