### ISSUE TITLE
Update the fiscal receipts accordingly to user feedback

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#243]
# Context
The fiscal receipts must be updated since some informations are now outdated.

The user provided us a corrected version of the fiscal receipts :
[fiscal-receipt-updated.pdf](https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura/files/5690531/fiscal-receipt-updated.pdf)

# Todo
- [x] Change the association's subtitle (top and bottom of the document)
- [x] Update the association's legal mentions
- [x] Remove the head office title and other crossed text
- [x] Change the association's email address
- [x] Add the treasurer signature at the end of the page first half
- [x] Remove the treasurer phone number

**Comment by Yann-BUTSCHER-EIRL** [comment]
For testing, we will submit the newly generated receipt to the end user.
I'll post the feedback if needed.

**Comment by LucileDT** [comment]
Are you sure that the email is with a `-`? I see a `.` but I might be wrong

**Comment by LucileDT** [comment]
I think it's good, we just need to be sure about the email address.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Seen with end user : It is a `.` so i'm updating the template.
