### ISSUE TITLE
Rework the donation page

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#269]
# Context
The donation detail page is a bit outdated compared to the membership detail page.
For harmonization sake and better readability, it would be nice the rework it.
The donation detail page should look like the membership detail page.

# Todo
- [x] Relabel "Date de règlement" to "Date du don" (won't do)
- [x] Add a box containing the donator information
  - [x] On click, go to the donator profile
- [x] Add a box containing the payment informations

**Comment by LucileDT** [comment]
@hundrex if you want to test it, you will need to switch to the `develop-sprint-11` branch
