### ISSUE TITLE
Postal codes starting with a 0 are truncated

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#270]
# Scenario
- Create/find an user that has an address which the postal code starts with 0 (e.g. 01300)
- Go to its profile

# Expected behavior
The postal code should display 5 characters (e.g 01300)

# Current behavior
The first character - 0 - is truncated, only 4 characters are shown. (e.g 1300)

# Todo
- [x] Temporaly add a leading 0 in the attribute getter (if needed)
- [x] Update the address FormType for it to save the postal code as a string
- [x] Make sure the first `0` is shown on :
  - [x] People detail page
  - [x] Member detail page
  - [x] Profile page
  - [x] Fiscal receipts

**Comment by Yann-BUTSCHER-EIRL** [comment]
A quick fix will be applied for the sprint 10 and a more durable fix will be done on sprint 11.

**Comment by Yann-BUTSCHER-EIRL** [comment]
Since the definitive fix is easy we decided to do all the fixes in the sprint 10.
