### ISSUE TITLE
Harmonize donation list with the membership list

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#272]
# Context
The donation list lacks readability since the donator is shown in one column, at the end of the table. 
This makes hard to the user to find the searched donator or even order the table by first name or last name.

# Todo
- [x] Remove the donator column
- [x] Add a new column containing the last name
   - [x] The last name must be uppercase
   - [x] This column must be on first position in the table
   - [x] This column must be sortable
- [x] Add a new column containing the first name
  - [x] This column must be placed after the last name
  - [x] This column must be sortable
