### ISSUE TITLE
Order people by lastname

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#273]
# Context
Since our application revolves around people, it would be easier, more intuitive and more similar if all the lists (table or dropdown) containing people would be sorted by their lastname, by default. 

# Todo
- [x] Add order by lastname when loading people from the database
- [x] Same when loading donations 
  - [x] Order by donator lastname
- [x] And memberships
  - [x] Order by member lastname 
  - [x] Take the person with the lastname's starting letter being closer to the start of the alphabet
