### ISSUE TITLE
All Name fields in tables should be in caps

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#276]
# Context
Name column in /donation shows values in caps. All other tables should do the same

# Todo
- [x] Put caps in name column of /member
- [x] Put caps in name column of /contact
- [x] Put caps in name column of /people
- [x] Put caps in name column of /membership
