### ISSUE TITLE
Receipt generation css and images are broken

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#282]
# Scenario
Go to the fiscal receipts page
Try to generate a receipt (year 2017 for exemple)

# Expected behavior
The image should be visible and the document prettily formatted

# Current behavior
The images are replaced by empty boxes and the document is badly formatted 

#Todo
- [x] Fix css links when generating the receipts from a worker
- [x] Fix images links when generating the receipts from a worker
- [x] Make sure the receipts generated from a controller are well formed after the fixes
