### ISSUE TITLE
Create a donation from a person's profile

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#286]
# Context

To better fit the user's workflow we need to be able to go to the donation creation form, by clicking on a button from a person's profile. The person will then be pre-selected in the newly opened creation form.

# Todo

- [x] Make the donation creation form accept a person id as an optional parameter
  - [x] If the parameter is given, the person should be pre-selected as donator 
- [x] In the person show page, add a button that redirect to the donation creation form
  - [x] The person's id should be passed as a parameter when redirecting
- [x] Make the buttons more stylized and user friendly

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT Can you add the button please? The optional parameter name is `person-id`
