### ISSUE TITLE
Add memberships and donations list on member details page

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#290]
# Context

To avoid clicking and make use of the page width, we should display a member donations and memberships directly on their page.

# Todo
- [x] get rid of the left menu (move buttons elsewhere)
- [x] rework member details page
- [x] add memberships list
  - [x] general information
  - [x] openable rows for details
- [x] add donations list
  - [x] general information
  - [x] openable rows for details
- [x] add payments list
  - [x] general information
