### ISSUE TITLE
Add the possibility to print the tags directly from the preview page 

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#302]
# Context
Since the tags generation is a fastidious process and the end user often doesn't need to download the generated pdf file, it would be nice to add a print button that will print the preview shown in the tag page.

# Todo
- [ ] Find a technical way to print only a certain part of the an HTML page
- [ ] Implements it via a button
- [ ] Implements it when hitting the print page shortcut (Ctrl + P)

**Comment by Yann-BUTSCHER-EIRL** [comment]
We can use CSS to enable the preview to be the only visible element when entering the print mode.

Examples are provided [here](https://www.tutorialspoint.com/How-to-print-a-page-using-JavaScript).
