### ISSUE TITLE
Use Yarn instead of Composer to manage DataTables

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#307]
# Context
Each time we update Structura, the composer install fails due to DataTables link being deprecated. We should stop using this method.

# Todo
- [x] remove installation process from composer
- [x] add package with Yarn
- [x] use webpack encore to compile
- [x] move our whole frontend architecture to the new one
