### ISSUE TITLE
Rework the people form in order to better manage data validation

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#319]
# Context
Recently we got multiple user feedback stating that the people form (create or edit) was not working properly.

One of the main reason is that each time the submitted data are not well formatted there is no front-end warning is shown to the user and no consistent error management is done when validating data in the back-end. 

Reworking the entire form and way of asserting data constraints is a lot of work but I would be beneficial and might save time in the future (with less bug fixing).

# Todo
- [ ] Update the `PeopleType` form to add front-end validation.
- [ ] Add back-end validation with a better entity mapping (see https://symfony.com/doc/4.4/validation.html)
- [ ] Add try/catch block when creating a people
  - This will prevent uncaught exceptions that blocks the user 
  - This will also help having a better way of logging exceptions
- [ ] Same thing when updating a people

**Comment by LucileDT** [comment]
I agree
