### ISSUE TITLE
Update to Symfony 5.4

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#320]
# Context
Since our current Symfony version is not maintained anymore it would be really nice to update Symfony, mainly for security and performance reasons.
It would also help remove deprecations notices as mentioned in #121.

# Todo
- [ ] Make a first update to Symfony 5.0 (major version change)
  - [ ] Update symfony composer packages 
  - [ ] Update other packages versions if needed to ensure compatibility 
  - [ ] Fix the errors
  - [ ] Fix the deprecations as much as possible
  - Use [UPGRADE-5.0.md](https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.0.md) to help you make code adjustments 
- [ ] Make a second update to Symfony 5.4 (minor version change)
  - [ ] Update symfony composer packages 
  - [ ] Update other packages versions if needed to ensure compatibility 
  - [ ] Fix the errors
  - [ ] Fix the deprecations as much as possible
  - Use [UPGRADE-5.4.md](https://github.com/symfony/symfony/blob/5.4/UPGRADE-5.4.md) to help you make code adjustments
