### ISSUE TITLE
Update to Symfony 6.3

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#322]
# Context
Now that Symfony has been updated to 5.4 we can continue for the same reasons mentions in #320 

# Todo
- [ ] Make an update to Symfony 6.3
  - [ ] Update symfony composer packages 
  - [ ] Update other packages versions if needed to ensure compatibility 
  - [ ] Fix the errors
  - [ ] Fix the deprecations as much as possible
  - Use [UPGRADE-6.0.md](https://github.com/symfony/symfony/blob/6.3/UPGRADE-6.0.md), [UPGRADE-6.1.md](https://github.com/symfony/symfony/blob/6.3/UPGRADE-6.1.md), [UPGRADE-6.2.md](https://github.com/symfony/symfony/blob/6.3/UPGRADE-6.2.md) and [UPGRADE-6.3.md](https://github.com/symfony/symfony/blob/6.3/UPGRADE-6.3.md) to help you make code adjustments
