### ISSUE TITLE
Formalisation of the branches structure for the project

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#44]
# Context
Currently, we use `master` to release stable versions of the application and `develop` to push our devs.
We will change it for a new model.
We will have three big "official" branches:
- `develop`: it is an unstable branch. We push our code on it, 
- `test`: it's an unstable branch. We merge on it:
  - `develop` each time we want to test it with Travis 
  - the hot fix branches we use to fix urgent bug in production
  - the PR made by lovely contributors who are not members of the project
  - `develop` each time a sprint is finished 
- `master`: it's a stable branch. We merge on it:
  - `test` each time a stable release is released
  - the hot fix branches when they have been tested and approved

It is possible to see other branches, used to hotfix or to develop big functionnalities without breaking dev env in `develop`. Those branches are unstable.

# Todo
- [x] write documentation about this structure
- [x] write documentation explaining how to create a pull request for people external to the project
- [ ] edit Travis configuration to make it listen only the `test` branch
- [ ] edit the post-merge hook to take in account this structure
