### ISSUE TITLE
Upgrade the project to Symfony 4.0 then to Symfony 4.2

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#50]
# Context
The differences between Symfony 3.4 and Symfony 4.0 are minor. The deprecated methods in 3.4 just desapear in 4.0 but otherwise the features are the same.

Then we should probably upgrade to 4.2 which is the next LTS version.

The faster we upgrade the project, the lesser code will need to be updated.

# Todo
- [x] Upgrade to Symfony 4.0 using this guide : https://symfonycasts.com/screencast/symfony4-upgrade
- [x] Upgrade to Symfony 4.1 using this guide : https://github.com/symfony/symfony/blob/4.1/UPGRADE-4.1.md
- [x] Upgrade to Symfony 4.2 using this guide : https://github.com/symfony/symfony/blob/4.2/UPGRADE-4.2.md
- [x] Other things listed in the comments

**Comment by Yann-BUTSCHER-EIRL** [comment]
There is no more deprecation warnings when running the project so we could be able to transition to 4.0 easily

**Comment by LucileDT** [comment]
Saw another interesting thing: we can show Symfony deprecation in unit tests, could you look at the official documentation?

**Comment by Yann-BUTSCHER-EIRL** [comment]
We already show them but there is no deprecation anymore.

After some testing I realized that we can't upgrade to 4.0 since Mink only support Symfony 2 and 3.
From this we have two obvious solutions : 
- Upgrade anyway and use something else than Mink for testing
- Keeping the project in Symfony 3.4 for now

**Comment by Yann-BUTSCHER-EIRL** [comment]
## Change made

- We are now using https://packagist.org/packages/symfony/maker-bundle instead of https://packagist.org/packages/sensio/generator-bundle
- https://packagist.org/packages/behat/mink is now required in "dev-master" version
    - This is not ideal but it's the only way to make it work with Symfony 4
    - We probably should insist on the fact that we need support for Symfony 4 on their GitHub
- Removing https://packagist.org/packages/doctrine/doctrine-fixtures-bundle (v 3.1) in order to upgrade to Symfony 4.0
    - We will need to install it again for Symfony 4.1

**Comment by Yann-BUTSCHER-EIRL** [comment]
The server has been upgraded in a new branch but there is thing we still need to do :
- Update the documentation
    - [  ] Install procedure
    - [  ] How to launch the server
    - [  ] How to run the tests
- [  ] Update sources to use the new flashbag
- [  ] Launch Chrome automatically when executing tests
- [  ] Launch the server in test env automatically when executing tests
- [  ] Find a more userfriendly way to run the server

**Comment by LucileDT** [comment]
I merged the branch on `develop`

**Comment by LucileDT** [comment]
I think we should separate the todo list in several issues, this one is too big

**Comment by Yann-BUTSCHER-EIRL** [comment]
Closing this issue since all the remaining work has been exported to separated issues.
