### ISSUE TITLE
Better support of roles

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#66]
# Context
We need to support the user's responsibilities in a better way. We talked about it in an internal meeting and come to some agreements.

# Todo
- [x] add a field to Responsibility to add an `automatic` field (boolean): if true, the field will be managed by the application and users will not be able to manually edit it.
  - [x] create the field
  - [x] migrate the data
  - [x] hide the automatic responsibilities from the different forms used to create/edit the users
- [x] implement the automation of:
  - [x] Inscrit.e
  - [x] ex-adhérent.e
- [x] check if it's possible to create automatic checks which throw exceptions when a rule defined in our internal responsibilities sheet is not observed (it as been done in a project I worked in, maybe I will find how to do by browsing the code).
