### ISSUE TITLE
Add a form verification on all e-mail address fields

### ISSUE THREAD

**Issue by Yann-BUTSCHER-EIRL** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#69]
# Context
We should make sure that every email addresses that we save in our DB is correct.

This would first prevent users from making mistakes (like forgetting the `@`) but also will reduce the error risk when sending emails (feature not implemented yet).

# Todo
- [x] Implement a JavaScript verification on all forms that are demanding an email address
    - [x] People creation/edit form
- [ ] Update functional tests to make sure that the verification works
