### ISSUE TITLE
[functionnal testing] User's related pages

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#76]
# Todo
- [ ] user creation `/user/new`
    - [x] access
    - [x] submit works
        - [x] inscrite by default on all account created
        - [x] username + password only
        - [x] each role works properly (see `https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd/wiki/C)-2.-Contribution-:-R%C3%B4les`)
    - [ ] submit doesn't work
        - [x] username already taken
        - [x] passwords not the same
        - [ ] each role works properly (see `https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd/wiki/C)-2.-Contribution-:-R%C3%B4les`) and throw error when they are not compatible
    - [x] button return
    - [x] breadcrumb
        - [x] from card
            - [x] accueil
            - [x] administration
            - [x] liste des utilisateurices
        - [x] from list
            - [x] accueil
            - [x] administration
            - [x] liste des utilisateurices
        - [x] by default
            - [x] accueil
            - [x] administration
            - [x] liste des utilisateurices
- [ ] user list `/user/`
    - [x] access
    - [ ] button create
    - [ ] button show profile
    - [ ] button edit profile
    - [ ] button delete profile
    - [ ] navigation
    - [ ] 10 users per list
    - [ ] filtering
        - [ ] id
        - [ ] username
        - [ ] role
    - [ ] breadcrumb
        - [ ] accueil
        - [ ] administration
- [ ] user edition `/user/{id}/edit`
    - [ ] access
    - [ ] button Supprimer l'utilisateurice 
    - [ ] username+roles form submit works
        - [ ] inscrite by default
        - [ ] username
        - [ ] each role works properly (see `https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd/wiki/C)-2.-Contribution-:-R%C3%B4les`)
    - [ ] username+roles form submit doesn't work
        - [ ] username already taken
        - [ ] each role works properly (see `https://github.com/LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd/wiki/C)-2.-Contribution-:-R%C3%B4les`) and throw error when they are not compatible
    - [ ] password form submit works
    - [ ] password form submit doesn't work
        - [ ] old password false
        - [ ] passwords not the same
    - [ ] breadcrumb
        - [ ] accueil
        - [ ] administration
        - [ ] liste des utilisateurices
- [ ] user profile `/user/{id}/`
    - [ ] access
    - [ ] button Profil
    - [ ] button Historique
    - [ ] button Edition
    - [ ] breadcrumb
        - [ ] accueil
        - [ ] administration
        - [ ] liste des utilisateurices
- [ ] profile `/profile/`
*not doable as the screen needs an update*
- [ ] profile edition `/profile/edit`
*not doable as the screen needs an update*
