### ISSUE TITLE
Standardize the user&member pages

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#79]
# Context
Currently, we have a lot of pages looking like other pages. We need to uniform those.

# Todo
- [x] members
    - [x] creation
        - [x] add return button (see user creation for an example)
        - [x] change the submit button label (see user creation for an example)
    - [x] edition
        - [x] add a delete button (see user edition for an example)
        - [x] add return button (see user creation for an example)
        - [x] change the submit button label for `Enregistrer les modifications`
        - [x] add `*` on mandatory field labels
- [x] users
    - [x] edition
        - [x] add `*` on mandatory field labels
    - [x] details
        - [x] add return button (see user creation for an example)
