### ISSUE TITLE
[functionnal testing] Miscelaneous pages

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#81]
# Todo
- [ ] login page
    - [ ] access
    - [ ] login works
    - [ ] login doesn't works
        - [ ] username incorrect
        - [ ] password incorrect
        - [ ] error database connection
- [ ] home page
    - [ ] access
- [ ] navbar
    - [ ] Adhérent.es button
        - [ ] shown
        - [ ] hidden
    - [ ] Administration button
        - [ ] shown
        - [ ] hidden
    - [ ] Mon profil button
    - [ ] Me déconnecter button
- [ ] administration page
    - [ ] access
    - [ ] Liste des comptes
    - [ ] Enregistrer un nouveau compte
