### ISSUE TITLE
Put all the form submit buttons into the views instead of the Types

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#86]
# Context
Currently, the submit buttons are both created in the Types and in the views. As explained in the documentation https://symfony.com/doc/current/best_practices/forms.html#form-button-configuration, the best practice is to put them only into the views.

# Todo
- [x] for each type
    - [x] add the submit button into the view (classes + icon + label)
    - [x] remove the submit button from the Types
