### ISSUE TITLE
Update the global directory

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#90]
# Context
We want a directory which can contains all the people close to the association. The current global directory needs some changes to be less specific.

# Todo
- [x] modify labels
  - [x] Top label: `Annuaire généraliste`
  - [x] breadcrumb:  `Annuaires` > `Annuaire généraliste`
  - [x] title: `Annuaire généraliste`
  - [x] add a column with the phone number of the user

**Comment by hundrex** [comment]
Ok for /people page, but whenever going to /people/X pages the breadcrumb is still "annuaire global"
