### ISSUE TITLE
Update top menu

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#91]
# Context
We now have more pages, we need to guide the user to the right one using the menu.

# Todo

To the left:

- [x] Accueil
- [x] Annuaires
  - [x] Adhérent.es
  - [x] Sympatisant.es
  - [x] Professionnels de santé
  - [x] Global
- [x] Adhésions
- [x] Dons

---

To the right:

- [x] Administration
- [x] username 
  - [x] Mon profil
  - [x] Me déconecter

**Comment by LucileDT** [comment]
@Parmifer as we said:
- [ ] disable the Annuaires > Adhérent.es button (but keep the view)
- [ ] enable the Annuaires > Global
- [ ] create the views using those of Adhérent.es

**Comment by LucileDT** [comment]
Good for me!
