### ISSUE TITLE
Add Membership

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#94]
# Context
We need to save when people subscribe to the association.

# Todo
- [x] using the MCD, create the class and it's attributes
- [x] migrate
- [x] using the mockup, create the CRUD
  - [x] list: mockup 3
  - [x] create: mockup 4
    - [x] people.s selection : no mockup 
  - [x] edit: mockup 4 (exported to #118 )
  - [x] read: no mockup

**Comment by Yann-BUTSCHER-EIRL** [comment]
A first version of the membership creation page is stable but we need to adjust few things that will be detailed in a separate issue.

**Comment by Yann-BUTSCHER-EIRL** [comment]
We're also creating a different issue for the edition page.
