### ISSUE TITLE
Add a global logging system to the application

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/structura#98]
# Context
We should add a logging system used everywhere in the application when there is a catched error. Thanks to this we should be able to debug more easily when an user encounter a bug.

# Todo
- [ ] Search in the documentation how to add a simple text logger
- [ ] Add a the logger class to the dependency injection system
- [ ] Implement the logger where it's needed
  - [ ] Try/Catch groups
- [ ] Add a var in the configuration file that will tell the application where to write the log file
